workspace 'Mobile'
inhibit_all_warnings!
version = '10.0'
platform :ios, version

def default_pods
  pod 'Kingfisher'
  pod 'Moya/RxSwift'
  pod 'Moya-ModelMapper/RxSwift'
  pod 'RxCocoa'
end

target 'Mobile' do
  use_frameworks!
  default_pods
end

target 'MobileUITests' do
  inherit! :search_paths
end

target 'MobileTests' do
  inherit! :search_paths
end

target 'Services' do
  use_frameworks!
  project '../Services/Services.xcodeproj'
  default_pods
end

target 'ServicesTV' do
  use_frameworks!
  project '../Services/Services.xcodeproj'
  default_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end